# ┌────────── minute (0 - 59)
# │ ┌────────── hour (0 - 23)
# │ │ ┌────────── day of the month (1 - 31)
# │ │ │ ┌────────── month (1 - 12)
# │ │ │ │ ┌────────── day of the week (0 - 6)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
# https://crontab.guru/
# Use this website to create you schedule

name: First Cron Job
on:
  # Triggers the workflow every 1 minute
  schedule:
    - cron: "*/1 * * * *"
jobs:
  say-hi:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: echo "Hello world"