name: General Workflow

on:
  push:
  workflow_call:
    inputs:
      IMAGE_TAG:
        type: string
        required: true

env:
  IS_VIA_WORKFLOW_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
  IS_PUSH_TO_DEFAULT_BRANCH: ${{ github.ref == vars.DEFAULT_BRANCH && github.event_name == 'push' }}

jobs:
  execute:
    name: General Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run Tests
        run: mvn -B clean verify --file pom.xml

      - name: Upload JAR File
        if: ${{ env.IS_VIA_WORKFLOW_DISPATCH == 'true' || env.IS_PUSH_TO_DEFAULT_BRANCH == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: application-jar
          path: target/*.jar

  publish-image:
    name: Publish Image
    if: ${{ (github.ref == vars.DEFAULT_BRANCH && github.event_name == 'push') || github.event_name == 'workflow_dispatch' }}
    needs: [ execute ]
    uses: ./.github/workflows/push-to-registry.yml
    with:
      IMAGE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.IMAGE_TAG || vars.TAG }}
    secrets: inherit


