name: General Workflow

on:
  push:
  workflow_call:
    inputs:
      branch-name:
        type: string
        required: true
      image-tag:
        type: string
        required: true

env:
  IS_WORKFLOW_CALL: ${{ github.event_name == 'workflow_call' }}
  IS_PUSH_EVENT: ${{ github.event_name == 'push' }}
  IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/improvements' }}

jobs:
  general-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run Tests
        run: mvn -B clean verify --file pom.xml

  push-to-dockerhub-from-master:
    uses: ./.github/workflows/push-to-registry.yml
    if: ${{ env.IS_MAIN_BRANCH == true && env.IS_PUSH_EVENT == true }}
    with:
      branch-name: improvements
      image-tag: ${{ vars.TAG }}

  push-to-dockerhub-from-branch:
    uses: ./.github/workflows/push-to-registry.yml
    if: ${{ env.IS_WORKFLOW_CALL == true }}
    with:
      branch-name: ${{ inputs.branch-name }}
      image-tag: ${{ inputs.image-tag }}

