name: General Workflow

on:
  push:
  workflow_call:
    inputs:
      branch-name:
        type: string
        required: true
      image-tag:
        type: string
        required: true

#env:
#  IS_WORKFLOW_CALL: ${{ github.event_name == 'workflow_call' }}
#  IS_PUSH_EVENT: ${{ github.event_name == 'push' }}
#  IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/improvements' }}

env:
  JAR_UPLOAD: ${{ (github.ref == 'refs/heads/improvements' && github.event_name == 'push') || github.event_name == 'workflow_call' }}

jobs:
  general-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run Tests
        run: mvn -B clean verify --file pom.xml

      - name: Upload JAR File
        if: ${{ env.JAR_UPLOAD == true }}
        uses: actions/upload-artifact@v2
        with:
          name: application-jar
          path: target/*.jar

  push-to-dockerhub-from-master:
    needs: [ general-workflow ]
    uses: ./.github/workflows/push-to-registry.yml
    if: ${{ github.ref == 'refs/heads/improvements' && github.event_name == 'push' }}
    with:
      branch-name: improvements
      image-tag: ${{ vars.TAG }}
    secrets: inherit

  push-to-dockerhub-from-branch:
    needs: [ general-workflow ]
    uses: ./.github/workflows/push-to-registry.yml
    if: ${{ github.event_name == 'workflow_call' }}
    with:
      branch-name: ${{ inputs.branch-name }}
      image-tag: ${{ inputs.image-tag }}
    secrets: inherit

