name: Promote Image
on:
  workflow_dispatch:
    inputs:
      source:
        type: string
        description: Give your source image tag here
      target:
        type: string
        description: Give you new tag here

jobs:
  retag_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{secrets.DOCKER_USERNAME}}/sample
      - name: Promote
        run: docker image tag ${{secrets.DOCKER_USERNAME}}/sample:${{github.event.inputs.source}} ${{secrets.DOCKER_USERNAME}}/sample:${{github.event.inputs.target}}

