name: Image Promotion
on:
  workflow_dispatch:
    inputs:
      source:
        type: string
        description: Give your source image tag here
      target:
        type: string
        description: Give you new tag here

jobs:
  Retag_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Pull image
        run: docker pull ${{secrets.DOCKER_USERNAME}}/sample:${{github.event.inputs.source}}
      - name: Retag Image
        run:  docker tag ${{secrets.DOCKER_USERNAME}}/sample:${{github.event.inputs.source}} ${{secrets.DOCKER_USERNAME}}/sample:${{github.event.inputs.target}}
      - name: Push retagged image
        run: docker push ${{secrets.DOCKER_USERNAME}}/sample:${{github.event.inputs.target}}

