name: Promote
on:
  workflow_dispatch:
    inputs:
      source:
        type: string
        description: Give your source image tag here
      target:
        type: string
        description: Give you new tag here

jobs:
  retag_image:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "${{github.event.inputs.source}} to ${{github.event.inputs.target}}"

