name: Promote Image
on:
  workflow_dispatch:
    inputs:
      source:
        type: string
        description: Give your source image tag here
      target:
        type: string
        description: Give you new tag here

jobs:
  retag_image:
    runs-on: ubuntu-latest
    steps:
      - name: Promote
        run: docker tag ${{github.event.inputs.source}} ${{secrets.DOCKER_USERNAME}}/sample:${{github.event.inputs.target}}

