name: Publish Image From Branch - ${{ github.event.inputs.branch-name }}
on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        type: string
        description: Enter Image Tag
        required: true

jobs:
  execute:
    name: Trigger General Workflow
    uses: ./.github/workflows/general-workflow.yml
    with:
      IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
    secrets: inherit
