name: Merge to master
on:
  workflow_call:
    inputs:
      branch-name:
        type: string
        required: true
      image-tag:
        type: string
        required: true

env:
  REPO_PATH: ${{secrets.DOCKER_USERNAME}}/sample:${{inputs.image-tag}}

jobs:
  docker:
    name: Push Image to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}

      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: application-jar
          path: target/*.jar

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t $REPO_PATH .

      - name: Push Image
        run: docker push $REPO_PATH




